version: "3"
services:

  youtrack:
    image: jetbrains/youtrack:2023.1.9452
    container_name: jetbrains_youtrack
    restart: always
    volumes:
      - ./data:/opt/youtrack/data
      - ./conf:/opt/youtrack/conf
      - ./logs:/opt/youtrack/logs
      - ./backups:/opt/youtrack/backups
    ports:
      - 8080:8080
